name: ml4g

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.12
  - numpy=2.3.3
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.7
  - ipykernel=7.0.1
  - pybigwig=0.3.24

  - pip
  - pip:
    - torch==2.8.0
    - tqdm==4.67.1